export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTIONS_TYPES = "FETCH_TRANSACTIONS_TYPES";
export const FETCH_TRANSACTIONS_STATUS = "FETCH_TRANSACTIONS_STATUS";
export const FETCH_AGENTS = "FETCH_AGENTS";
export const FETCH_AGENTS_MANAGER = "FETCH_AGENTS_MANAGER";
export const DASHBOARD_BREAKDOWN = "DASHBOARD_BREAKDOWN";
export const DASHBOARD_TRANSACTION_DETAILS = "DASHBOARD_TRANSACTION_DETAILS";
export const FETCH_AUDIT = "FETCH_AUDIT";
export const AGENT_PURSE = "AGENT_PURSE";
export const CENTRAL_PURSE = "CENTRAL_PURSE";
export const ACTIVATION_CODE = "ACTIVATION_CODE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const FETCH_STATE = "FETCH_STATE";
export const FETCH_LGA = "FETCH_LGA";
export const FETCH_BANK = "FETCH_BANK";
export const CREATE_AGENTS_MANAGER = "CREATE_AGENTS_MANAGER";
export const FETCH_BANK_TERMINAL = "FETCH_BANK_TERMINAL";
export const ACTIVATE_ASSIGN_TERMINAL = "ACTIVATE_ASSIGN_TERMINAL";
export const UNACTIVATE_ASSIGN_TERMINAL = "UNACTIVATE_ASSIGN_TERMINAL";
export const CREATE_AGENTS = "CREATE_AGENTS";
export const AGENT_MANAGER_SETTLEMENT = "AGENT_MANAGER_SETTLEMENT";
export const CREDIT_DEBIT_PURSE = "CREDIT_DEBIT_PURSE"
export const FETCH_ROLE_GROUP = "FETCH_ROLE_GROUP"
export const FETCH_ROLE = "FETCH_ROLE"
export const CREATE_ROLE_GROUP = "CREATE_ROLE_GROUP"
export const FETCH_API_VERSION = "FETCH_API_VERSION"
export const CREATE_API_VERSION = "CREATE_API_VERSION"
export const DELETE_API_VERSION = "DELETE_API_VERSION"
export const FETCH_ADMIN_USERS = "FETCH_ADMIN_USERS"
export const CREATE_ADMIN = "CREATE_ADMIN"
export const UPDATE_ADMIN = "UPDATE_ADMIN"
export const UPDATE_ROLE_GROUP = "UPDATE_ROLE_GROUP"
export const FETCH_TRANSACTIONS_SINGLE = "FETCH_TRANSACTIONS_SINGLE"
export const PURSE_BALANCE_SUMMARY = "PURSE_BALANCE_SUMMARY"
export const FETCH_AMBASSADOR_AGENTS = "FETCH_AMBASSADOR_AGENTS"
export const ACTIVATE_DEACTIVATE_USER = "ACTIVATE_DEACTIVATE_USER"
export const RESET_AGENT_PASSWORD = "RESET_AGENT_PASSWORD"
export const UPDATE_AGENT = "UPDATE_AGENT"
export const MAXIMUM_RANGE = "MAXIMUM_RANGE"
export const CONVIENIENCE_FEE = "CONVIENIENCE_FEE"
export const UPDATE_FEE = "UPDATE_FEE"
export const CREATE_CONVIENCE_FEE = "CREATE_CONVIENCE_FEE"














