export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_AGENTS = "FETCH_AGENTS";
export const FETCH_AGENTS_MANAGER = "FETCH_AGENTS_MANAGER";
export const DASHBOARD_BREAKDOWN = "DASHBOARD_BREAKDOWN";
export const DASHBOARD_TRANSACTION_DETAILS = "DASHBOARD_TRANSACTION_DETAILS";
export const FETCH_AUDIT = "FETCH_AUDIT";
export const AGENT_PURSE = "AGENT_PURSE";
export const CENTRAL_PURSE = "CENTRAL_PURS";
export const ACTIVATION_CODE = "ACTIVATION_CODE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const FETCH_STATE = "FETCH_STATE";
export const FETCH_LGA = "FETCH_LGA";
export const FETCH_BANK = "FETCH_BANK";
export const CREATE_AGENTS_MANAGER = "CREATE_AGENTS_MANAGER";
export const FETCH_BANK_TERMINAL = "FETCH_BANK_TERMINAL";
export const ACTIVATE_ASSIGN_TERMINAL = "ACTIVATE_ASSIGN_TERMINAL";
export const UNACTIVATE_ASSIGN_TERMINAL = "UNACTIVATE_ASSIGN_TERMINAL";
export const CREATE_AGENTS = "CREATE_AGENTS"; 
export const AGENT_MANAGER_SETTLEMENT = "AGENT_MANAGER_SETTLEMENT";


